Repository robunye/diario-viagens, pull requests merged in 2022-06, with the labels that each got.

#15 Adição ng add @angular/fire
  .firebaserc
  angular.json
  firebase.json
  package.json
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: documentation

#17 Estilização e implementação de método para Login
  src/app/auth/components/cadastro/cadastro.component.html
  src/app/auth/components/cadastro/cadastro.component.ts
  src/app/auth/components/login/login.component.html
  src/app/auth/components/login/login.component.scss
  src/app/auth/components/login/login.component.ts
  src/app/core/services/auth/auth.service.ts
  src/index.html
Labels: documentation, enhancement

#21 implementei o recurso de ReCaptcha nos formulários de login e cadastro
  package-lock.json
  package.json
  src/app/auth/auth.module.ts
  src/app/auth/components/login/login.component.html
  src/app/auth/components/login/login.component.scss
  src/app/auth/components/login/login.component.ts
Labels: enhancement

#23 Padronização da página de Cadastro
  src/app/auth/components/cadastro/cadastro.component.html
  src/app/auth/components/cadastro/cadastro.component.scss
  src/app/auth/components/cadastro/cadastro.component.ts
  src/app/auth/components/login/login.component.html
  src/app/auth/components/login/login.component.scss
  src/app/auth/components/login/login.component.ts
  src/app/auth/components/usuario-nao-verificado/usuario-nao-verificado.component.html
  src/app/auth/components/usuario-nao-verificado/usuario-nao-verificado.component.scss
Labels: documentation

#31 Implementação de link nas imagens
  src/app/home/components/landing-page/landing-page.component.html
  src/app/home/components/landing-page/landing-page.component.scss
  src/assets/img/kwe.jpg
Labels: documentation

#33 Implementação de bate-papo interativo.
  src/app/app.module.ts
  src/app/chat/chat-routing.module.ts
  src/app/chat/chat.module.ts
  src/app/chat/components/feed/feed.component.html
  src/app/chat/components/feed/feed.component.scss
  src/app/chat/components/feed/feed.component.spec.ts
  src/app/chat/components/feed/feed.component.ts
  src/app/chat/components/message/message.component.html
  src/app/chat/components/message/message.component.scss
  src/app/chat/components/message/message.component.spec.ts
  src/app/chat/components/message/message.component.ts
  src/app/core/components/navbar/navbar.component.html
  src/app/core/models/message.ts
  src/app/core/services/chat/chat.service.spec.ts
  src/app/core/services/chat/chat.service.ts
Labels: enhancement

#36 Melhorias gerais
  src/app/dashboard/dashboard.component.html
  src/app/home/components/landing-page/landing-page.component.html
  src/app/home/components/landing-page/landing-page.component.scss
  src/app/shared/components/loader/loader.component.html
Labels: documentation

#38 Hover do botão cadastrar página lading page.
  src/app/home/components/landing-page/landing-page.component.html
Labels: documentation

#39 Clean code: Remover os comentários didáticos
  src/app/core/models/converter.ts
  src/app/core/models/diario.ts
  src/app/core/services/auth/auth.service.ts
  src/app/core/services/chat/chat.service.ts
  src/app/core/services/dashboard/dashboard.service.ts
  src/app/core/services/diarios/diarios.service.ts
  src/app/core/services/upload/upload.service.ts
Labels: documentation
